experiment_name: "no-angle-constraint"
model_name: "convnext_tiny"
num_epochs: 20
learning_rate: 0.0001
weight_decay: 0.0
margin: 0.75
batch_size: 64
data: {
  "train_dir": "data/oculariris/open-world/left-eye/train",
  "test_dir": "data/oculariris/open-world/left-eye/test",
}
max_anchor_negative_angle_diff: null