experiment_name: "pom-0"
model_name: "stn_convnext_tiny"
num_epochs: 20
learning_rate: 0.00005
weight_decay: 0.0
margin: 0.75
batch_size: 64
data: {
  "train_dir": "data/oculariris/open-world/left-eye/train",
  "test_dir": "data/oculariris/open-world/left-eye/test",
}
max_anchor_negative_angle_diff: 0